/*
Raiana Zaman
 */

package javaapplication4;

/**
 *
 * @author raianazaman
 */
public class loginWindow extends javax.swing.JFrame {

    /**
     * Creates new form loginWindow
     */
    public loginWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UserInpur_ID = new javax.swing.JButton();
        LogIn_PW = new javax.swing.JButton();
        UserInput_pw = new javax.swing.JButton();
        LogIn_ID = new javax.swing.JButton();
        SignInWithGoogle = new javax.swing.JButton();
        SignIn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Log In");
        setBackground(new java.awt.Color(204, 204, 204));

        UserInpur_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserInpur_IDActionPerformed(evt);
            }
        });

        LogIn_PW.setText("Password:");
        LogIn_PW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogIn_PWActionPerformed(evt);
            }
        });

        UserInput_pw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserInput_pwActionPerformed(evt);
            }
        });

        LogIn_ID.setText("ID:");
        LogIn_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogIn_IDActionPerformed(evt);
            }
        });

        SignInWithGoogle.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        SignInWithGoogle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication4/login-with-google-button-png-1.png"))); // NOI18N
        SignInWithGoogle.setText("Sign In with Google ");
        SignInWithGoogle.setToolTipText("");
        SignInWithGoogle.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        SignInWithGoogle.setDoubleBuffered(true);
        SignInWithGoogle.setIconTextGap(0);
        SignInWithGoogle.setIgnoreRepaint(true);
        SignInWithGoogle.setInheritsPopupMenu(true);
        SignInWithGoogle.setRolloverEnabled(true);
        SignInWithGoogle.setVerifyInputWhenFocusTarget(false);
        SignInWithGoogle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignInWithGoogleActionPerformed(evt);
            }
        });

        SignIn.setText("Sign In");
        SignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignInActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(90, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LogIn_PW, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(UserInput_pw, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LogIn_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(UserInpur_ID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(SignInWithGoogle, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SignIn, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(82, 82, 82))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(SignInWithGoogle, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(UserInpur_ID, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(LogIn_ID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LogIn_PW, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(UserInput_pw, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(46, 46, 46)
                .addComponent(SignIn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(197, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void LogIn_PWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogIn_PWActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LogIn_PWActionPerformed

    private void UserInpur_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserInpur_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserInpur_IDActionPerformed

    private void UserInput_pwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserInput_pwActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserInput_pwActionPerformed

    private void SignInWithGoogleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignInWithGoogleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SignInWithGoogleActionPerformed

    private void SignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignInActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SignInActionPerformed

    private void LogIn_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogIn_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LogIn_IDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LogIn_ID;
    private javax.swing.JButton LogIn_PW;
    private javax.swing.JButton SignIn;
    private javax.swing.JButton SignInWithGoogle;
    private javax.swing.JButton UserInpur_ID;
    private javax.swing.JButton UserInput_pw;
    // End of variables declaration//GEN-END:variables
}
